Fix powerpc build failure
Build fails on powerpc because of recent build infrastructure
changes:

  test/mgen/mgen-mgen.o: In function `dependent_read':
  /home/ravi/numatop-orig/test/mgen/mgen.c:354: undefined reference to `arch__dependent_read'
  ./.libs/libnumatop.a(os_util.o): In function `calibrate_cpuinfo':
  /home/ravi/numatop-orig/common/os/os_util.c:173: undefined reference to `arch__cpuinfo_freq'
  ./.libs/libnumatop.a(os_util.o): In function `calibrate_by_tsc':
  /home/ravi/numatop-orig/common/os/os_util.c:259: undefined reference to `rdtsc'
  /home/ravi/numatop-orig/common/os/os_util.c:261: undefined reference to `rdtsc'
  ./.libs/libnumatop.a(pfwrapper.o): In function `profiling_sample_read':
  ...

Fix this by testing proper values of host_cpu.

Signed-off-by: Ravi Bangoria <ravi.bangoria@linux.ibm.com>